version: '2.0'
services:
  backend:
    build: ./src/backend/
    ports:
    - "8000:8000"
    depends_on:
      - database
  
  frontend:
    build: ./src/frontend/
    ports:
    - "4000:4000"
    depends_on:
      - backend

  database:
    image: "bitnami/elasticsearch:latest"